// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  NEXT_PUBLIC_GITHUB_URL: string;

  NEXT_PUBLIC_REDIRECT_URL: string;
  NEXT_PUBLIC_REDIRECT_TEXT: string;
  NEXT_PUBLIC_REDIRECT_HIDDEN: boolean;
}
